# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dtrack-data-pv
  namespace: dtrack
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dtrack-data-pvc
  namespace: dtrack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

